---
title: "Final Project"
author: "Bridget Wojcik"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Actors Data Set
**Introduce your data using complete sentences.**  What kind of data set are you looking at? Why did you choose this data set?

#load the data set
```{r actors}
#Load the correct packages to open the data set
library(dyplr) 
library(readr)

#read the csv file (Insert your own name and location of the data set) 
Actors <- read_csv ("/Users/bridgetwojcik/Downloads/actors.csv")
```

## Research Question 1

Does who the Actor is effect what their total gross is?

```{r pressure, echo=FALSE}
# Load necessary libraries
library(ggplot2)
library(stringr)  

ggplot(Actors, aes(x = str_wrap(Actor, width = 10), y = `Total Gross`)) +
  geom_point() +  # Create a scatterplot
  labs(title = "Scatterplot of Actor by Total Gross",  # Set plot title
       x = "Actor",  # Set x-axis label
       y = "Total Gross") +  # Set y-axis label
  theme(axis.text.x = element_text(angle = 75, hjust = 1, size = 4))  # Adjust x-axis text angle and size
```

#EDA2
```{r, echo= FALSE}
# Create a bar plot
ggplot(Actors, aes(x = str_wrap(Actor, width = 10), y = `Total Gross`)) +
  geom_bar(stat = "identity", fill = "red", color = "black") +
  labs(title = "Bar Plot of Actor by Total Gross",
       x = "Actor",
       y = "Total Gross") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1, size = 5))


```

##Research Question 2 

Is there a significant difference in actor and their total gross and their number of movies? 

```{r}
# Convert "actor" to character
Actors$Actor <- as.character(Actors$Actor)
Actors$Num_Mov <- as.numeric(Actors$`Number of Movies`)


# Create a bar plot
ggplot(Actors, aes(x = Actor, y = Num_Mov)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Number of Movies by Actor",
       x = "Actor",
       y = "Number of Movies")

# Load necessary libraries
library(ggplot2)
library(stringr)  


# Load necessary libraries
library(ggplot2)
library(stringr)  

ggplot(Actors, aes(x = str_wrap(Actor, width = 10), y = `Total Gross`)) +
  geom_point() +  # Create a scatterplot
  labs(title = "Scatterplot of Actor by Total Gross",  # Set plot title
       x = "Actor",  # Set x-axis label
       y = "Total Gross") +  # Set y-axis label
  theme(axis.text.x = element_text(angle = 75, hjust = 1, size = 4))  # Adjust x-axis text angle and size
        
```
